name = "BootlegCassette"
uuid = "7e930afe-c91a-4d40-8977-8548870aff83"
authors = ["MasonProtter <mason.protter@icloud.com>"]
version = "0.1.0"

[deps]
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"

[compat]
julia = "1"
IRTools = "0.4.2"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg"]